services:
  backend:
    build:
      context: .
      dockerfile_inline: |
        FROM linuxserver/unrar:7.1.10 AS unrar-layer
        FROM gradle:9.3.1-jdk25-alpine
        RUN apk add --no-cache libstdc++ libgcc
        COPY --from=unrar-layer /usr/bin/unrar-alpine /usr/local/bin/unrar
    command: sh -c "cd /booklore-api && ./gradlew bootRun"
    ports:
      - "${BACKEND_PORT:-6060}:6060"
      - "127.0.0.1:${REMOTE_DEBUG_PORT:-5005}:5005"
    environment:
      - DATABASE_URL=jdbc:mariadb://backend_db:3306/grimmory
      - DATABASE_USERNAME=grimmory
      - DATABASE_PASSWORD=grimmory
      - REMOTE_DEBUG_ENABLED=true
      - ALLOWED_ORIGINS=http://localhost:4200
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend_db
    volumes:
      - './booklore-api:/booklore-api'
      - /booklore-api/build
      - /booklore-api/.gradle
      - ./shared/data:/app/data
      - ./shared/books:/books
      - ./shared/bookdrop:/bookdrop

  backend_db:
    image: mariadb:11.4
    container_name: backend_db
    volumes:
      - backend_db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=grimmory
      - MYSQL_DATABASE=grimmory
      - MYSQL_USER=grimmory
      - MYSQL_PASSWORD=grimmory
    ports:
      - "${DB_PORT:-3366}:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-pgrimmory" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ui:
    image: node:24-alpine
    command: sh -c "cd /angular-app && corepack enable && corepack yarn install --immutable && corepack yarn ng serve --host 0.0.0.0 --watch --configuration development"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - './frontend:/angular-app'

        # you can have node_modules in a volume. however, if you enable this, expect trouble in some IDEs, as the deps are not available anymore
        # - node_modules:/angular-app/node_modules

    ports:
      - "${FRONTEND_PORT:-4200}:4200"

volumes:
  node_modules:
  backend_db:
