package org.booklore.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum RuleField {
    @JsonProperty("library")
    LIBRARY,
    @JsonProperty("shelf")
    SHELF,
    @JsonProperty("title")
    TITLE,
    @JsonProperty("subtitle")
    SUBTITLE,
    @JsonProperty("authors")
    AUTHORS,
    @JsonProperty("categories")
    CATEGORIES,
    @JsonProperty("publisher")
    PUBLISHER,
    @JsonProperty("publishedDate")
    PUBLISHED_DATE,
    @JsonProperty("seriesName")
    SERIES_NAME,
    @JsonProperty("seriesNumber")
    SERIES_NUMBER,
    @JsonProperty("seriesTotal")
    SERIES_TOTAL,
    @JsonProperty("pageCount")
    PAGE_COUNT,
    @JsonProperty("language")
    LANGUAGE,
    @JsonProperty("isbn13")
    ISBN13,
    @JsonProperty("isbn10")
    ISBN10,
    @JsonProperty("amazonRating")
    AMAZON_RATING,
    @JsonProperty("amazonReviewCount")
    AMAZON_REVIEW_COUNT,
    @JsonProperty("goodreadsRating")
    GOODREADS_RATING,
    @JsonProperty("goodreadsReviewCount")
    GOODREADS_REVIEW_COUNT,
    @JsonProperty("hardcoverRating")
    HARDCOVER_RATING,
    @JsonProperty("hardcoverReviewCount")
    HARDCOVER_REVIEW_COUNT,
    @JsonProperty("ranobedbRating")
    RANOBEDB_RATING,
    @JsonProperty("personalRating")
    PERSONAL_RATING,
    @JsonProperty("fileType")
    FILE_TYPE,
    @JsonProperty("fileSize")
    FILE_SIZE,
    @JsonProperty("readStatus")
    READ_STATUS,
    @JsonProperty("dateFinished")
    DATE_FINISHED,
    @JsonProperty("lastReadTime")
    LAST_READ_TIME,
    @JsonProperty("metadataScore")
    METADATA_SCORE,
    @JsonProperty("moods")
    MOODS,
    @JsonProperty("tags")
    TAGS,
    @JsonProperty("genre")
    GENRE,
    @JsonProperty("ageRating")
    AGE_RATING,
    @JsonProperty("contentRating")
    CONTENT_RATING,
    @JsonProperty("addedOn")
    ADDED_ON,
    @JsonProperty("lubimyczytacRating")
    LUBIMYCZYTAC_RATING,
    @JsonProperty("description")
    DESCRIPTION,
    @JsonProperty("narrator")
    NARRATOR,
    @JsonProperty("audibleRating")
    AUDIBLE_RATING,
    @JsonProperty("audibleReviewCount")
    AUDIBLE_REVIEW_COUNT,
    @JsonProperty("abridged")
    ABRIDGED,
    @JsonProperty("audiobookDuration")
    AUDIOBOOK_DURATION,
    @JsonProperty("audiobookCodec")
    AUDIOBOOK_CODEC,
    @JsonProperty("audiobookChapterCount")
    AUDIOBOOK_CHAPTER_COUNT,
    @JsonProperty("audiobookBitrate")
    AUDIOBOOK_BITRATE,
    @JsonProperty("isPhysical")
    IS_PHYSICAL,
    @JsonProperty("seriesStatus")
    SERIES_STATUS,
    @JsonProperty("seriesGaps")
    SERIES_GAPS,
    @JsonProperty("seriesPosition")
    SERIES_POSITION,
    @JsonProperty("readingProgress")
    READING_PROGRESS,
    @JsonProperty("metadataPresence")
    METADATA_PRESENCE
}

