ALTER TABLE library MODIFY COLUMN icon VARCHAR(64) NULL;
ALTER TABLE library MODIFY COLUMN icon_type VARCHAR(255) NULL;

ALTER TABLE magic_shelf MODIFY COLUMN icon VARCHAR(64) NULL;
ALTER TABLE magic_shelf MODIFY COLUMN icon_type VARCHAR(255) NULL;

ALTER TABLE shelf MODIFY COLUMN icon VARCHAR(64) NULL;
ALTER TABLE shelf MODIFY COLUMN icon_type VARCHAR(255) NULL;
