ALTER TABLE author ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE author ADD COLUMN IF NOT EXISTS asin VARCHAR(20);
ALTER TABLE author ADD COLUMN IF NOT EXISTS name_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE author ADD COLUMN IF NOT EXISTS description_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE author ADD COLUMN IF NOT EXISTS asin_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE author ADD COLUMN IF NOT EXISTS photo_locked BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_author_asin ON author (asin);
