ALTER TABLE book_metadata MODIFY COLUMN title VARCHAR(1000);
ALTER TABLE book_metadata MODIFY COLUMN subtitle VARCHAR(1000);
ALTER TABLE book_metadata MODIFY COLUMN publisher VARCHAR(1000);
ALTER TABLE book_metadata MODIFY COLUMN isbn_10 VARCHAR(64);
ALTER TABLE book_metadata MODIFY COLUMN isbn_13 VARCHAR(64);
ALTER TABLE book_metadata MODIFY COLUMN thumbnail VARCHAR(2000);
ALTER TABLE book_metadata MODIFY COLUMN series_name VARCHAR(1000);
ALTER TABLE book_metadata MODIFY COLUMN cover VARCHAR(2000);